version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=yiya_accounts
      - POSTGRES_USER=thony
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
